#!/usr/bin/env python3
"""Stage 4 — Catalog builder: merge profile + relations + descriptions into
one catalog document, plus human-readable renderings.

READ-ONLY: this tool never modifies the source DB. It does NOT emit any
COMMENT ON / DDL. Existing DB comments are preserved verbatim (rule-based,
no LLM) and shown alongside the generated description for review.

Outputs:
  out/catalog.json         — the catalog: every table/column with type, stats
                             summary, keys, description, confidence, evidence,
                             and the ORIGINAL DB comment (if any)
  out/data_dictionary.md   — Markdown data dictionary
  out/erd.mmd              — Mermaid ER diagram
"""
from config import PGSCHEMA, out_path, load_json, dump_json


def build_catalog(profile, relations, desc):
    pks = relations.get("primary_keys", {})
    fks = relations.get("foreign_keys", [])
    fk_by_child = {}
    for f in fks:
        fk_by_child.setdefault(f["child_table"], []).append(f)

    catalog = {
        "schema": PGSCHEMA,
        "model": desc.get("model"),
        "database": desc.get("db", {}),
        "tables": [],
    }
    for tname, tinfo in sorted(profile["tables"].items()):
        td = desc["tables"].get(tname, {})
        cols_desc = {c["name"]: c for c in td.get("columns", [])}
        pk = pks.get(tname)
        tfks = fk_by_child.get(tname, [])
        fk_by_col = {f["child_column"]: f for f in tfks}
        columns = []
        for c in tinfo["columns"]:
            d = cols_desc.get(c["name"], {})
            fk = fk_by_col.get(c["name"])
            # ORIGINAL DB comment, preserved verbatim (rule-based, not LLM)
            orig = c.get("existing_comment")
            columns.append({
                "name": c["name"],
                "type": c["data_type"],
                "nullable": c["nullable"],
                "is_pk": bool(pk and c["name"] in pk["columns"]),
                "fk": (f'{fk["parent_table"]}.{fk["parent_column"]}'
                       if fk else None),
                "fk_source": fk["source"] if fk else None,
                "description": d.get("description", ""),
                "original_comment": orig,           # 원본 DB 주석 (없으면 None)
                "has_original": bool(orig),
                "confidence": d.get("confidence"),
                "evidence": d.get("evidence"),
                "data_unverified": d.get("data_unverified", False),
                "stats": {
                    "distinct_ratio": c["stats"].get("distinct_ratio"),
                    "null_ratio": c["stats"].get("null_ratio"),
                    "examples": c["stats"].get("examples", [])[:3],
                },
            })
        catalog["tables"].append({
            "name": tname,
            "rowcount": tinfo["rowcount"],
            "description": td.get("table_description", ""),
            "original_comment": tinfo.get("table_comment"),   # 원본 테이블 주석
            "has_original": bool(tinfo.get("table_comment")),
            "reasoning": td.get("reasoning", ""),
            "sanity_revised": td.get("sanity_revised", False),
            "primary_key": pk,
            "foreign_keys": [
                {"column": f["child_column"],
                 "ref": f'{f["parent_table"]}.{f["parent_column"]}',
                 "confidence": f.get("confidence"), "source": f["source"]}
                for f in tfks],
            "columns": columns,
        })
    return catalog


def render_markdown(catalog):
    lines = [f"# Data Dictionary — schema `{catalog['schema']}`\n"]
    db = catalog["database"]
    lines.append(f"**Domain:** {db.get('domain', '?')}\n")
    lines.append(f"{db.get('db_description', '')}\n")
    lines.append(f"_Generated by {catalog.get('model', '?')} (db2doc v2)._\n")
    for t in catalog["tables"]:
        lines.append(f"\n## `{t['name']}`  ({t['rowcount']} rows)\n")
        lines.append(f"{t['description']}\n")
        if t["primary_key"]:
            cols = ", ".join(f"`{c}`" for c in t["primary_key"]["columns"])
            lines.append(f"- **PK** ({t['primary_key']['source']}): {cols}")
        for f in t["foreign_keys"]:
            lines.append(f"- **FK** ({f['source']}, conf {f['confidence']}): "
                         f"`{f['column']}` → `{f['ref']}`")
        if t.get("original_comment"):
            lines.append(f"\n> 원본 DB 주석: {t['original_comment']}")
        lines.append("\n| Column | Type | Key | Description | 원본 주석 | Conf |")
        lines.append("|---|---|---|---|---|---|")
        for c in t["columns"]:
            key = "PK" if c["is_pk"] else (f"FK→{c['fk']}" if c["fk"] else "")
            d = (c["description"] or "").replace("|", "\\|")
            orig = (c.get("original_comment") or "").replace("|", "\\|")
            conf = (f"{c['confidence']:.2f}"
                    if isinstance(c["confidence"], (int, float)) else "")
            if c["data_unverified"]:
                conf += " ⚠"
            lines.append(f"| `{c['name']}` | {c['type']} | {key} | {d} "
                         f"| {orig} | {conf} |")
    return "\n".join(lines) + "\n"


def render_mermaid(catalog):
    out = ["erDiagram"]
    for t in catalog["tables"]:
        out.append(f"    {t['name']} {{")
        if t["primary_key"]:
            for c in t["primary_key"]["columns"]:
                out.append(f"        id {c} PK")
        out.append("    }")
    for t in catalog["tables"]:
        for f in t["foreign_keys"]:
            parent = f["ref"].split(".")[0]
            out.append(f'    {parent} ||--o{{ {t["name"]} : "{f["column"]}"')
    return "\n".join(out) + "\n"


def main():
    profile = load_json(out_path("profile.json"))
    relations = load_json(out_path("relations.json"))
    desc = load_json(out_path("descriptions.json"))

    catalog = build_catalog(profile, relations, desc)
    dump_json(catalog, out_path("catalog.json"))
    with open(out_path("data_dictionary.md"), "w") as f:
        f.write(render_markdown(catalog))
    with open(out_path("erd.mmd"), "w") as f:
        f.write(render_mermaid(catalog))
    ncols = sum(len(t["columns"]) for t in catalog["tables"])
    n_orig = sum(1 for t in catalog["tables"] for c in t["columns"]
                 if c.get("original_comment"))
    print(f">> catalog: {len(catalog['tables'])} tables / {ncols} columns "
          f"({n_orig} columns had original DB comments, preserved)")
    print(">> wrote out/catalog.json, data_dictionary.md, erd.mmd "
          "(read-only — no COMMENT/DDL emitted)")


if __name__ == "__main__":
    main()
