"""Render descriptions into artifacts (extracted from render/render.py).

to_sql is dialect-aware: PostgreSQL uses COMMENT ON; MySQL uses
ALTER TABLE ... MODIFY/CHANGE with COMMENT (column-level) and
ALTER TABLE ... COMMENT (table-level).
"""
import csv
import io


def _q(value):
    return "'" + str(value).replace("'", "''") + "'"


def to_markdown(desc, relations, schema):
    lines = [f"# Data Dictionary — schema `{schema}`\n"]
    db = desc.get("db", {})
    lines.append(f"**Domain:** {db.get('domain','?')}\n")
    lines.append(f"{db.get('db_description','')}\n")
    lines.append(f"_Generated by {desc.get('model','?')}._\n")
    pks = relations.get("primary_keys", {})
    fks = relations.get("foreign_keys", [])
    for table, tdesc in sorted(desc["tables"].items()):
        lines.append(f"\n## `{table}`\n")
        lines.append(f"{tdesc['table_description']}\n")
        pk = pks.get(table, {}).get("column")
        if pk:
            lines.append(f"- **Primary key (recovered):** `{pk}`")
        for f in [x for x in fks if x["child_table"] == table]:
            lines.append(f"- **FK (recovered):** `{f['child_column']}` → "
                         f"`{f['parent_table']}.{f['parent_column']}` "
                         f"(incl={f['inclusion']})")
        lines.append("\n| Column | Description | Confidence |")
        lines.append("|---|---|---|")
        for c in tdesc["columns"]:
            d = c["description"].replace("|", "\\|")
            conf = c.get("confidence")
            cs = f"{conf:.2f}" if isinstance(conf, (int, float)) else ""
            lines.append(f"| `{c['name']}` | {d} | {cs} |")
    return "\n".join(lines) + "\n"


def to_sql(desc, schema, dialect):
    """COMMENT statements. dialect in {'postgresql','mysql','mariadb'}."""
    out = [f"-- COMMENT statements for schema {schema} ({dialect})"]
    is_mysql = dialect in ("mysql", "mariadb")
    for table, tdesc in sorted(desc["tables"].items()):
        td = tdesc["table_description"]
        if is_mysql:
            out.append(f"ALTER TABLE `{schema}`.`{table}` COMMENT = {_q(td)};")
            # column comments in MySQL require the full column definition; emit a
            # template the DBA completes (type kept generic to stay safe).
            for c in tdesc["columns"]:
                out.append(
                    f"-- ALTER TABLE `{schema}`.`{table}` "
                    f"MODIFY `{c['name']}` <type> COMMENT {_q(c['description'])};")
        else:
            out.append(f'COMMENT ON TABLE "{schema}"."{table}" IS {_q(td)};')
            for c in tdesc["columns"]:
                out.append(f'COMMENT ON COLUMN "{schema}"."{table}"."{c["name"]}" '
                           f'IS {_q(c["description"])};')
    return "\n".join(out) + "\n"


def to_csv(desc):
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["table", "column", "description", "confidence"])
    for table, tdesc in sorted(desc["tables"].items()):
        w.writerow([table, "", tdesc["table_description"], ""])
        for c in tdesc["columns"]:
            w.writerow([table, c["name"], c["description"], c.get("confidence", "")])
    return buf.getvalue()


def to_mermaid(desc, relations):
    out = ["erDiagram"]
    pks = relations.get("primary_keys", {})
    for table in sorted(desc["tables"].keys()):
        pk = pks.get(table, {}).get("column")
        out.append(f"    {table} {{")
        if pk:
            out.append(f"        id {pk} PK")
        out.append("    }")
    for f in relations.get("foreign_keys", []):
        out.append(f"    {f['parent_table']} ||--o{{ {f['child_table']} : "
                   f"\"{f['child_column']}\"")
    return "\n".join(out) + "\n"
