#!/usr/bin/env python3
"""Render generated descriptions into human-readable artifacts.

Reads out/descriptions.json + out/relations.json and writes:
  out/data_dictionary.md   — Markdown data dictionary
  out/comments.sql         — COMMENT ON statements to push docs back into the DB
  out/metadata.csv         — flat CSV (table, column, type, description, confidence)
  out/erd.mmd              — Mermaid ER diagram from recovered relations
"""
import os
import sys
import csv

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from common import PGSCHEMA, out_path, load_json  # noqa: E402


def render_markdown(desc, relations):
    lines = []
    db = desc["db"]
    lines.append(f"# Data Dictionary — schema `{PGSCHEMA}`\n")
    lines.append(f"**Domain:** {db.get('domain','?')}\n")
    lines.append(f"{db.get('db_description','')}\n")
    lines.append(f"_Generated by {desc.get('model','?')}._\n")
    pks = relations.get("primary_keys", {})
    fks = relations.get("foreign_keys", [])
    for table, tdesc in sorted(desc["tables"].items()):
        lines.append(f"\n## `{table}`\n")
        lines.append(f"{tdesc['table_description']}\n")
        pk = pks.get(table, {}).get("column")
        if pk:
            lines.append(f"- **Primary key (recovered):** `{pk}`")
        tfks = [f for f in fks if f["child_table"] == table]
        for f in tfks:
            lines.append(f"- **FK (recovered):** `{f['child_column']}` → "
                         f"`{f['parent_table']}.{f['parent_column']}` "
                         f"(incl={f['inclusion']})")
        lines.append("\n| Column | Description | Confidence |")
        lines.append("|---|---|---|")
        for c in tdesc["columns"]:
            d = c["description"].replace("|", "\\|")
            lines.append(f"| `{c['name']}` | {d} | {c.get('confidence',''):.2f} |"
                         if isinstance(c.get("confidence"), (int, float))
                         else f"| `{c['name']}` | {d} | |")
    return "\n".join(lines) + "\n"


def render_sql(desc):
    out = [f"-- COMMENT statements generated for schema {PGSCHEMA}"]
    for table, tdesc in sorted(desc["tables"].items()):
        td = tdesc["table_description"].replace("'", "''")
        out.append(f"COMMENT ON TABLE \"{PGSCHEMA}\".\"{table}\" IS '{td}';")
        for c in tdesc["columns"]:
            cd = c["description"].replace("'", "''")
            out.append(f"COMMENT ON COLUMN \"{PGSCHEMA}\".\"{table}\".\"{c['name']}\" IS '{cd}';")
    return "\n".join(out) + "\n"


def render_csv(desc, path):
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["table", "column", "description", "confidence"])
        for table, tdesc in sorted(desc["tables"].items()):
            w.writerow([table, "", tdesc["table_description"], ""])
            for c in tdesc["columns"]:
                w.writerow([table, c["name"], c["description"], c.get("confidence", "")])


def render_mermaid(desc, relations):
    out = ["erDiagram"]
    # entities with key columns only (keep diagram readable)
    pks = relations.get("primary_keys", {})
    for table in sorted(desc["tables"].keys()):
        pk = pks.get(table, {}).get("column")
        out.append(f"    {table} {{")
        if pk:
            out.append(f"        id {pk} PK")
        out.append("    }")
    for f in relations.get("foreign_keys", []):
        out.append(f"    {f['parent_table']} ||--o{{ {f['child_table']} : "
                   f"\"{f['child_column']}\"")
    return "\n".join(out) + "\n"


def main():
    desc = load_json(out_path("descriptions.json"))
    relations = load_json(out_path("relations.json"))

    md = out_path("data_dictionary.md")
    with open(md, "w") as f:
        f.write(render_markdown(desc, relations))
    sql = out_path("comments.sql")
    with open(sql, "w") as f:
        f.write(render_sql(desc))
    render_csv(desc, out_path("metadata.csv"))
    mmd = out_path("erd.mmd")
    with open(mmd, "w") as f:
        f.write(render_mermaid(desc, relations))

    print(">> wrote out/data_dictionary.md, comments.sql, metadata.csv, erd.mmd")


if __name__ == "__main__":
    main()
